name: Docker production CI

on:
  push:
    branches:
      - main
    
  workflow_dispatch:    

env:
  TAG: ${{ github.sha }}
  
jobs:

  backend:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build backen Image
        run: docker build -t binayadevops/kutu-backend:${TAG} ./backend

      - name : Push the backend Images
        run: docker push binayadevops/kutu-backend:${TAG}
   
  frontend:
    
    needs: backend

    runs-on: ubuntu-latest

    steps:

      - name: checkout code
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Build Frontend Image
        run: docker build -t binayadevops/kutu-frontend:${TAG} ./frontend

      - name : Push the Frontend Images
        run: docker push binayadevops/kutu-frontend:${TAG}

